services:
  - type: web
    name: boasvindas-multimodelos
    env: node
    plan: free
    buildCommand: npm install && node server/db-init.js
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    build:
      env:
        NODE_VERSION: 18.20.2
